version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://urbanai_user:${DB_PASSWORD}@db:3306/urbanai
    env_file:
      - .env.production
    networks:
      - urbanai-network

  # MySQL Database
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=urbanai
      - MYSQL_USER=urbanai_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - urbanai-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - urbanai-network

  # Nginx for reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    networks:
      - urbanai-network

volumes:
  urbanai-db-data:
    driver: local

networks:
  urbanai-network:
    driver: bridge 